CREATE TABLE users
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) CHECK (role IN ('ROLE_USER', 'ROLE_ADMIN')) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);